### PR TITLE
[#106] Implement healthcheck script

### LINKED ISSUE #106: Service account creation fails randomly
While doing a blueprint upgrade containing baseline and scm dogu, the blueprint upgrade randomly fails, because a service account for baseline in scm cannot be created during installation of baseline.

### PR DESCRIPTION
**Pull request by nfranzeck**
Because of race conditions during the blueprint upgrade between baseline and scm, we need to wait until scm is started completely. This should be ensured by a http health check. Currently, scm does not provide a dedicated health endpoint that can be used without authentication.

Resolves #106

### CODE REVIEW

File: resources/healthcheck.sh [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+
+# Perform health check against scm endpoint
+HTTP_STATUS=$(curl --write-out "%{http_code}" --silent --output /dev/null --max-time 10 http://localhost:8080/scm/api/v2 -H "${CES_TOKEN_HEADER}: ${API_TOKEN}") || HTTP_STATUS=0
+if [[ "$HTTP_STATUS" -ne 200 ]]; then
+  echo "scm is unhealthy"
+  HEALTH_STATUS=1
+fi
+
+# Successful http check means tcp port is also available
+doguctl state "ready"
```
Comment (ppxl) [inline resources/healthcheck.sh:32]: I understand the `doguctl state ready` at the end of this file but why here?

File: resources/healthcheck.sh [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+fi
+
+# Check general health status
+if [[ "$HEALTH_STATUS" -ne 0 ]]; then
+  doguctl state "unhealthy"
+  exit 1
+fi
+
+doguctl state "ready"
+exit 0
```
Comment (ppxl) [inline resources/healthcheck.sh:49]: I would like to recommend to make this script testable with source guards, especially now that is so lean and nice. Could I also encourage you to write some BATS tests?

**Review by ppxl — CHANGES_REQUESTED** [review]
This looks like a really nice change, thanks for that! 👏🏾 

I am currently testing the change but I did found some issues, among them one that does not show up in the Diff tab:

- There is a changelog entry missing in `CHANGELOG.md`. 
- There is a release note entry missing in `docs/gui/release_notes_*.md`.

File: resources/healthcheck.sh [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+
+HEALTH_STATUS=0
+
+# connection token
+API_TOKEN=$(doguctl config --encrypted ${CES_TOKEN_CONFIGURATION_KEY})
+
+# Perform health check against scm endpoint
+HTTP_STATUS=$(curl --write-out "%{http_code}" --silent --output /dev/null --max-time 10 http://localhost:8080/scm/api/v2 -H "${CES_TOKEN_HEADER}: ${API_TOKEN}") || HTTP_STATUS=0
+if [[ "$HTTP_STATUS" -ne 200 ]]; then
+  echo "scm is unhealthy"
```
[the remark this answers is not in the document]
Comment (nfranzeck) [reply resources/healthcheck.sh]: the echo message now also prints the http status code in case of an error

File: resources/healthcheck.sh (hunk 1 above)
Comment (nfranzeck) [reply resources/healthcheck.sh]: That's because of the use of `dogu healthy scm` right after this statement. the healthcheck in the dogu.json defines "tcp" as well as "state". So if the state isn't set to ready `doguctl healthy` has never the chance to become true.

File: resources/healthcheck.sh (hunk 2 above)
Comment (nfranzeck) [reply resources/healthcheck.sh]: source guards as well as BATS test has been added

**Comment by nfranzeck** [comment]
Beside the comments from the review, I have also changed:

- Add Makefile + makefiles
- Update Jenkinsfile:
  - Update build-libs
  - add stage for bats test
  - Update integrations tests as well as stage in jenkins

**Comment by cloudgge** [comment]
LGTM
